corpus = "file.toml"
dataset = "bios"
prefix = "./data/"
index = "Dataset-idx"
[[analyzers]]
	method = "ngram-word"
	ngram = 1
	[[analyzers.filter]]
		type = "icu-tokenizer"
	[[analyzers.filter]]
		type = "lowercase"
[query-runner]
	query-id-start = 0
	query-path = "FacultyDataset-queries.txt"
	timeout = 120
